AddonId: SteamGameTransferUtility_c2dac2df-44c9-4f47-8555-c8d134c4f400
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/SteamGameTransferUtility_c2dac2df-44c9-4f47-8555-c8d134c4f400_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/SteamGameTransferUtility_c2dac2df-44c9-4f47-8555-c8d134c4f400_2_1.pext
    Changelog:
      - Updated localizations
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/SteamGameTransferUtility_c2dac2df-44c9-4f47-8555-c8d134c4f400_2_2.pext
    Changelog:
    - Updated localizations
    - Update to PlayniteSDK.6.0.0
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/SteamGameTransferUtility_c2dac2df-44c9-4f47-8555-c8d134c4f400_2_3.pext
    Changelog:
    - Updated localizations
  - Version: 2.4
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/SteamGameTransferUtility_c2dac2df-44c9-4f47-8555-c8d134c4f400_2_4.pext
    Changelog:
    - Updated localizations
    - Updated to Playnite SDK 6.1.0