AddonId: Installation_Status_Updater
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/Installation_Status_Updater_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
      - Added several settings to make it configurable
      - New functionality to add a tag with the drive letter the game is installed on
  - Version: 2.0.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/Installation_Status_Updater_2_0_1.pext
    Changelog:
      - Fix localization strings not loading
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/Installation_Status_Updater_2_1.pext
    Changelog:
      - Updated localizations
      - Fix incorrect detection in GameActions of type "File"
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/Installation_Status_Updater_2_2.pext
    Changelog:
    - Fix setting game actions as not Play Action when checking their status
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta3/Installation_Status_Updater_2_3.pext
    Changelog:
    - Updated localizations
  - Version: 2.4
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-22
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta4/Installation_Status_Updater_2_4.pext
    Changelog:
    - Updated localizations
  - Version: 2.5
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/Installation_Status_Updater_2_5.pext
    Changelog:
    - Updated localizations
    - Update to PlayniteSDK.6.0.0
    - Add functionality to update installation statuses when files in directories change
    - Add functionality to update installation statuses when storage devices are inserted or removed
  - Version: 2.6
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/Installation_Status_Updater_2_6.pext
    Changelog:
    - Fix in case drive is not ready when scanning connected drives
  - Version: 2.7
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/Installation_Status_Updater_2_7.pext
    Changelog:
    - Updated localizations
    - Fix all games added in Playnite 9 version being skipped if option to skip games handled by library plugins has been enabled
  - Version: 2.8
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/Installation_Status_Updater_2_8.pext
    Changelog:
    - Updated localizations
    - Updated to Playnite SDK 6.1.0
  - Version: 2.9
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/Installation_Status_Updater_2_9.pext
    Changelog:
    - Updated localizations
  - Version: 2.10
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-27
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/Installation_Status_Updater_2_10.pext
    Changelog:
    - Updated localizations
  - Version: 2.11
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/Installation_Status_Updater_2_11.pext
    Changelog:
    - Updated localizations
    - Reworked storage devices insert and removal detection
  - Version: 2.12
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-04
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/Installation_Status_Updater_2_12.pext
    Changelog:
    - Updated localizations
  - Version: 2.13
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-12
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/Installation_Status_Updater_2_13.pext
    Changelog:
    - Updated localizations
  - Version: 2.14
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/Installation_Status_Updater_2_14.pext
    Changelog:
    - Fixed extension causing Playnite windows to not be centered when created when Playnite is not the foreground window
  - Version: 2.15
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/Installation_Status_Updater_2_15.pext
    Changelog:
    - Updated localizations
  - Version: 2.16
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/Installation_Status_Updater_2_16.pext
    Changelog:
    - Fix installation status of games added as Microsoft Store Application not being correctly detected
  - Version: 2.17
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-16
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/Installation_Status_Updater_2_17.pext
    Changelog:
    - Updated localizations
  - Version: 2.18
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/Installation_Status_Updater_2_18.pext
    Changelog:
    - Updated localizations
    - Show notification when games are marked as installed or uninstalled and a dialog is not shown
  - Version: 2.19
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/Installation_Status_Updater_2_19.pext
    Changelog:
    - Updated localizations
  - Version: 2.20
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-22
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/Installation_Status_Updater_2_20.pext
    Changelog:
    - Updated localizations
  - Version: 2.21
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/Installation_Status_Updater_2_21.pext
    Changelog:
    - Updated localizations
    - Updated to Playnite SDK 6.2.2
  - Version: 2.22
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/Installation_Status_Updater_2_22.pext
    Changelog:
    - Updated localizations
  - Version: 2.23
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/Installation_Status_Updater_2_23.pext
    Changelog:
    - Updated localizations
    - Added option to detect game installation status when using the Install button
  - Version: 2.24
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/Installation_Status_Updater_2_24.pext
    Changelog:
    - Updated localizations
  - Version: 2.25
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.9/Installation_Status_Updater_2_25.pext
    Changelog:
    - Improved extension codebase structure
    - Misc improvements
  - Version: 2.26
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.17_881638e7/Installation_Status_Updater_2_26.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.27
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.25_aae44e45/Installation_Status_Updater_2_27.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.28
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.30_901ef791/Installation_Status_Updater_2_28.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.29
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-03
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.03_3ad2d023/Installation_Status_Updater_2_29.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.30
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-05-06
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.05.06_bad3b108/Installation_Status_Updater_2_30.pext
    Changelog:
    - 'Fix adding a Tag instead of a Feature in the menu item to add the ignore feature'
  - Version: 2.31
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-06-11
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.06.11_f6b6813d/Installation_Status_Updater_2_31.pext
    Changelog:
    - 'Performance improvements to games processing'
  - Version: 2.32
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-06-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.06.18_251f0687/Installation_Status_Updater_2_32.pext
    Changelog:
    - 'Updated localizations'
    - 'Fix errors when game paths contain invalid characters'
  - Version: 2.33
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-07-08
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.07.08_f601c982/Installation_Status_Updater_2_33.pext
    Changelog:
    - 'Performance improvements to games processing'
  - Version: 2.34
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-07-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.07.15_13b6fe2b/Installation_Status_Updater_2_34.pext
    Changelog:
    - 'Fix failing to add some notifications after one has been displayed'
  - Version: 2.35
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-11-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.11.14_873c946b/Installation_Status_Updater_2_35.pext
    Changelog:
    - 'Fix scan not working if game paths use variables'
  - Version: 2.36
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-12-11
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.12.11_3fe9a125/Installation_Status_Updater_2_36.pext
    Changelog:
    - 'Updated localizations'
    - 'Support to open window that displays installation status changes after status scan'
  - Version: 2.37
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-01-07
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.01.07_6064640d/Installation_Status_Updater_2_37.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.38
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-02-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.02.15_7796d0ce/Installation_Status_Updater_2_38.pext
    Changelog:
    - 'Updated links'
  - Version: 2.39
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-07-19
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.07.19_7051579c/Installation_Status_Updater_2_39.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.40
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-08-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.08.18_ceff63a9/Installation_Status_Updater_2_40.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.41
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-12-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.12.30_242d6d8c/Installation_Status_Updater_2_41.pext
    Changelog:
    - 'Improved: Minor improvements to detection process'
  - Version: 2.42
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-12-31
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.12.31_5bc47234/Installation_Status_Updater_2_42.pext
    Changelog:
    - 'Fixed: Setting incorrect installation status during scan'
  - Version: 2.43
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-02-04
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.02.04_c8608bd5/Installation_Status_Updater_2_43.pext
    Changelog:
    - 'Changed: Updated localizations'
  - Version: 2.44
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.03.17_527a9df9/Installation_Status_Updater_2_44.pext
    Changelog:
    - 'Added: : Support to detect games from library plugins by detecting their installation directory (Disabled by default)'
    - 'Changed: Moved menu items related to skipping functionality from the main menu to the right click game menu'
    - 'Changed: Updated localizations'
  - Version: 2.45
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-03-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.03.18_9107fafe/Installation_Status_Updater_2_45.pext
    Changelog:
    - 'Fixed: Incorrect detection of games installation statuts in some circumstances'
  - Version: 2.46
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-03-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.03.20_449a50a2/Installation_Status_Updater_2_46.pext
    Changelog:
    - 'Changed: Updated localizations'
    - 'Improved: Small improvement to detection of games from library plugins'
  - Version: 2.47
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-03-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.03.20_3f7181b3/Installation_Status_Updater_2_47.pext
    Changelog:
    - 'Changed: Enabled option to only use actions marked as Play Actions for game install status detection by default'
  - Version: 2.48
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-05-12
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.05.12_b43337e1/Installation_Status_Updater_2_48.pext
    Changelog:
    - 'Changed: Updated localizations'