AddonId: SpecialKHelper_71349310-9ed8-4bf5-8bf2-e92cdb222748
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-10
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/SpecialKHelper_71349310-9ed8-4bf5-8bf2-e92cdb222748_1_0.pext
    Changelog:
    - Initial release