AddonId: GameRelations_a4c15d63-9ab4-4d96-9a0c-8f9b35d43a1f
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-11-11
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.11.11_3bf6575c/GameRelations_a4c15d63-9ab4-4d96-9a0c-8f9b35d43a1f_1_0.pext
    Changelog:
    - 'Initial release'
  - Version: 1.1
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-11-11
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.11.11_d180d50c/GameRelations_a4c15d63-9ab4-4d96-9a0c-8f9b35d43a1f_1_1.pext
    Changelog:
    - 'Fixed: Cover height setting not being applied to covers'
  - Version: 1.2
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-11-11
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.11.11_6837a4d5/GameRelations_a4c15d63-9ab4-4d96-9a0c-8f9b35d43a1f_1_2.pext
    Changelog:
    - 'Added: Option to exclude certain tags when matching games in the similarity games list'
    - 'Improved: Performance when displaying a large number of games'
    - 'Fixed: Certain texts in settings not using Playnite styling'
    - 'Fixed: Minor fixes during game matching procedure'
  - Version: 1.3
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-11-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.11.13_97d6d8ad/GameRelations_a4c15d63-9ab4-4d96-9a0c-8f9b35d43a1f_1_3.pext
    Changelog:
    - 'Added: Option to exclude certain genres and categories when matching games in the similarity games list'
    - 'Added: Option to exclude games from the same series in the similarity games list. Enabled by default.'
    - 'Improved: Matching algorithm to improve detection of similar games'
    - 'Changed: Updated localizations'
    - 'Changed: Increasing maximum value of games to display to 100'
    - 'Fixed: Fixed error during matching that could prevent certain games from displaying in similar games in rare circumstances'
  - Version: 1.4
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-11-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.11.28_0f949552/GameRelations_a4c15d63-9ab4-4d96-9a0c-8f9b35d43a1f_1_4.pext
    Changelog:
    - 'Changed: Updated localizations'
  - Version: 1.5
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-02-04
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.02.04_c8608bd5/GameRelations_a4c15d63-9ab4-4d96-9a0c-8f9b35d43a1f_1_5.pext
    Changelog:
    - 'Changed: Updated localizations'
  - Version: 1.6
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.03.17_527a9df9/GameRelations_a4c15d63-9ab4-4d96-9a0c-8f9b35d43a1f_1_6.pext
    Changelog:
    - 'Changed: Updated localizations'
  - Version: 1.7
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-05-12
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.05.12_b43337e1/GameRelations_a4c15d63-9ab4-4d96-9a0c-8f9b35d43a1f_1_7.pext
    Changelog:
    - 'Changed: Updated localizations'