AddonId: PlayState
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/PlayState_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/PlayState_2_1.pext
    Changelog:
      - Updated localizations
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/PlayState_2_2.pext
    Changelog:
    - Updated localizations
  - Version: 2.3
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/PlayState_2_3.pext
    Changelog:
    - Updated localizations
  - Version: 2.4
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/PlayState_2_4.pext
    Changelog:
    - Updated localizations
  - Version: 2.5
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-27
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/PlayState_2_5.pext
    Changelog:
    - Updated localizations
    - Removed AutoHotkey dependency
    - Suspend/Resume hotkey is configurable in settings
    - 'Game skip feature changed to "[PlayState] Blacklist"'
    - General fixes and improvements as part of the extension rewrite
  - Version: 2.6
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/PlayState_2_6.pext
    Changelog:
    - Updated localizations
    - "Add note in settings that indicates that used hotkey can't be used in other applications"
    - Changed default hotkey combination to Shift+Alt+A
  - Version: 2.7
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-01
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/PlayState_2_7.pext
    Changelog:
    - Updated localizations
  - Version: 2.8
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/PlayState_2_8.pext
    Changelog:
    - Updated localizations
    - Added optional functionality to substract suspended time from game playtime after it is stopped
    - Added optional functionality to only suspend playtime count when suspending the game. Game processes are not suspended with this suspension mode.
    - 'Added optional functionality to force the suspend only playtime and not game processes for games that have a feature named "[PlayState] Suspend Playtime only"'
    - Changed descriptions in suspend dialogs to reflect if game processes or only playtime count was suspended
  - Version: 2.9
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-07
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/PlayState_2_9.pext
    Changelog:
    - Updated localizations
    - Fix being able to save invalid hotkeys without modifiers in settings
    - Add menu items to configure or remove configuration to force playtime suspend only of selected games
  - Version: 2.10
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-09
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.2/PlayState_2_10.pext
    Changelog:
    - Updated localizations
  - Version: 2.11
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-12
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/PlayState_2_11.pext
    Changelog:
    - Updated localizations
  - Version: 2.12
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/PlayState_2_12.pext
    Changelog:
    - Fixed extension causing Playnite windows to not be centered when created when Playnite is not the foreground window