AddonId: CoverCollageMaker_7713ea8c-cdec-46ac-b603-6d666515f3da
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2025-05-26
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2025.05.26_4de645ff/CoverCollageMaker_7713ea8c-cdec-46ac-b603-6d666515f3da_1_0.pext
    Changelog:
    - 'Initial release'