AddonId: CooperativeModesImporter_9767ac15-6e26-4e4c-9d69-f6838625dde3
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/CooperativeModesImporter_9767ac15-6e26-4e4c-9d69-f6838625dde3_1_0.pext
    Changelog:
    - Updated localizations