AddonId: SteamSearch_78c7912a-32bb-4a42-8485-d348d10023ac
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.3.0
    ReleaseDate: 2022-07-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.08.21_54d33423/SteamSearch_78c7912a-32bb-4a42-8485-d348d10023ac_1_0.pext
    Changelog:
    - 'Initial release'
  - Version: 1.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-01-07
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.01.07_6064640d/SteamSearch_78c7912a-32bb-4a42-8485-d348d10023ac_1_1.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.2
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2023-02-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.02.15_7796d0ce/SteamSearch_78c7912a-32bb-4a42-8485-d348d10023ac_1_2.pext
    Changelog:
    - 'Updated links'
  - Version: 1.3
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2023-07-19
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.07.19_7051579c/SteamSearch_78c7912a-32bb-4a42-8485-d348d10023ac_1_3.pext
    Changelog:
    - 'Fix Steam game searches failing after Steam web changes'
  - Version: 1.4
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2023-08-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.08.18_ceff63a9/SteamSearch_78c7912a-32bb-4a42-8485-d348d10023ac_1_4.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.5
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2023-09-12
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.09.12_e3d10655/SteamSearch_78c7912a-32bb-4a42-8485-d348d10023ac_1_5.pext
    Changelog:
    - 'Fix searches being incorrect when the search included certain special characters'
  - Version: 1.6
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2023-10-10
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.10.10_141fd33d/SteamSearch_78c7912a-32bb-4a42-8485-d348d10023ac_1_6.pext
    Changelog:
    - 'Fixed: Failing to obtain Steam store search results in some searches'
  - Version: 1.7
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2023-11-11
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.11.11_3bf6575c/SteamSearch_78c7912a-32bb-4a42-8485-d348d10023ac_1_7.pext
    Changelog:
    - 'Improved: Processing of internet requests'
  - Version: 1.8
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2024-02-04
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.02.04_c8608bd5/SteamSearch_78c7912a-32bb-4a42-8485-d348d10023ac_1_8.pext
    Changelog:
    - 'Changed: Updated localizations'
  - Version: 1.9
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2024-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.03.17_527a9df9/SteamSearch_78c7912a-32bb-4a42-8485-d348d10023ac_1_9.pext
    Changelog:
    - 'Changed: Updated localizations'