AddonId: GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_1.pext
    Changelog:
      - Updated localizations
      - Fix overview showing when no game is selected
      - Fix using an incorrect localization string during certain dialogs
      - Fix requesting the same catalog data twice
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_2.pext
    Changelog:
    - Updated localizations
    - Update to PlayniteSDK.6.0.0
  - Version: 2.3
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_3.pext
    Changelog:
    - Updated localizations
    - Updated to Playnite SDK 6.1.0
  - Version: 2.4
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_4.pext
    Changelog:
    - Updated localizations
  - Version: 2.5
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-09
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.2/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_5.pext
    Changelog:
    - Updated localizations
  - Version: 2.6
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_6.pext
    Changelog:
    - Updated localizations
    - Added button in catalog window to open game in Xbox app
  - Version: 2.7
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-16
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_7.pext
    Changelog:
    - Updated localizations