AddonId: Steam_Viewer_0a3edabb-065f-4056-a294-d6bc0656e2ac
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/Steam_Viewer_0a3edabb-065f-4056-a294-d6bc0656e2ac_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/Steam_Viewer_0a3edabb-065f-4056-a294-d6bc0656e2ac_2_1.pext
    Changelog:
      - Updated localizations
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/Steam_Viewer_0a3edabb-065f-4056-a294-d6bc0656e2ac_2_2.pext
    Changelog:
    - Updated localizations
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/Steam_Viewer_0a3edabb-065f-4056-a294-d6bc0656e2ac_2_3.pext
    Changelog:
    - Updated localizations
    - Fix using incorrect localization string
  - Version: 2.4
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/Steam_Viewer_0a3edabb-065f-4056-a294-d6bc0656e2ac_2_4.pext
    Changelog:
    - Updated localizations
  - Version: 2.5
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/Steam_Viewer_0a3edabb-065f-4056-a294-d6bc0656e2ac_2_5.pext
    Changelog:
    - Updated localizations
  - Version: 2.6
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/Steam_Viewer_0a3edabb-065f-4056-a294-d6bc0656e2ac_2_6.pext
    Changelog:
    - Updated localizations
  - Version: 2.7
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/Steam_Viewer_0a3edabb-065f-4056-a294-d6bc0656e2ac_2_7.pext
    Changelog:
    - Updated localizations
  - Version: 2.8
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/Steam_Viewer_0a3edabb-065f-4056-a294-d6bc0656e2ac_2_8.pext
    Changelog:
    - Updated localizations
  - Version: 2.9
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/Steam_Viewer_0a3edabb-065f-4056-a294-d6bc0656e2ac_2_9.pext
    Changelog:
    - Updated localizations
  - Version: 2.10
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-06-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.06.18_251f0687/Steam_Viewer_0a3edabb-065f-4056-a294-d6bc0656e2ac_2_10.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.11
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-08-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.08.18_ceff63a9/Steam_Viewer_0a3edabb-065f-4056-a294-d6bc0656e2ac_2_11.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.12
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-10-10
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.10.10_141fd33d/Steam_Viewer_0a3edabb-065f-4056-a294-d6bc0656e2ac_2_12.pext
    Changelog:
    - 'Improved: Improvements to how Steam calls are handled'
  - Version: 2.13
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2024-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.03.17_527a9df9/Steam_Viewer_0a3edabb-065f-4056-a294-d6bc0656e2ac_2_13.pext
    Changelog:
    - 'Changed: Updated localizations'
  - Version: 2.14
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2024-05-12
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.05.12_b43337e1/Steam_Viewer_0a3edabb-065f-4056-a294-d6bc0656e2ac_2_14.pext
    Changelog:
    - 'Changed: Updated localizations'
  - Version: 3.0
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-11-16
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.11.16_92da71fc/Steam_Viewer_0a3edabb-065f-4056-a294-d6bc0656e2ac_3_0.pext
    Changelog:
    - 'Added: Option to configure if Steam web urls, like store or discussion pages, should be opened in the web browser or Steam client'
    - 'Added: New menu items to open the Steam input or Properties windows of Steam games'
    - 'Changed: The extension has been renamed from "Steam Viewer" to "Steam Shortcuts"'
    - 'Changed: Items in menu will now display an icon'
    - 'Changed: Items in menu will now be in a single list and separated by categories'
    - 'Changed: The extension has been completely rewritten in C# to improve performance, reliability, and maintainability, while also enabling easier future feature additions'
  - Version: 3.1
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-11-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.11.28_0d43de8b/Steam_Viewer_0a3edabb-065f-4056-a294-d6bc0656e2ac_3_1.pext
    Changelog:
    - 'Changed: Menu items for opening Steam URLs are now available for non-Steam games, provided they have a Steam store link added'