AddonId: NVIDIA_GeForce_Now_Enabler
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/NVIDIA_GeForce_Now_Enabler_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support