AddonId: SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_1.pext
    Changelog:
      - Updated localizations
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_2.pext
    Changelog:
    - Updated localizations
    - Rewriten from scratch as a plugin
    - Options are now available in extensions settings section
  - Version: 2.3
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_3.pext
    Changelog:
    - Fix background music not stopping when launching a game in Fullscreen Mode
    - Updated to Playnite SDK 6.1.0
  - Version: 2.4
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_4.pext
    Changelog:
    - Updated localizations
    - Fix splash windows always showing in main screen, even if Playnite is in a secondary monitor
  - Version: 2.5
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_5.pext
    Changelog:
    - Updated localizations
  - Version: 2.6
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-27
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_6.pext
    Changelog:
    - Updated localizations
  - Version: 2.7
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-12
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_7.pext
    Changelog:
    - Updated localizations