AddonId: Image_Cache_Size_Saver
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/Image_Cache_Size_Saver_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support