AddonId: Installation_Status_Updater
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/Installation_Status_Updater_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
      - Added several settings to make it configurable
      - New functionality to add a tag with the drive letter the game is installed on
  - Version: 2.0.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/Installation_Status_Updater_2_0_1.pext
    Changelog:
      - Fix localization strings not loading
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/Installation_Status_Updater_2_1.pext
    Changelog:
      - Updated localizations
      - Fix incorrect detection in GameActions of type "File"
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/Installation_Status_Updater_2_2.pext
    Changelog:
    - Fix setting game actions as not Play Action when checking their status
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta3/Installation_Status_Updater_2_3.pext
    Changelog:
    - Updated localizations
  - Version: 2.4
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-22
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta4/Installation_Status_Updater_2_4.pext
    Changelog:
    - Updated localizations
  - Version: 2.5
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/Installation_Status_Updater_2_5.pext
    Changelog:
    - Updated localizations
    - Update to PlayniteSDK.6.0.0
    - Add functionality to update installation statuses when files in directories change
    - Add functionality to update installation statuses when storage devices are inserted or removed