AddonId: Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support