AddonId: FilterPresetsQuickLauncher_ef9df36c-24c2-418c-8468-eed95a09d950
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-08-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.08.18_720fb69d/FilterPresetsQuickLauncher_ef9df36c-24c2-418c-8468-eed95a09d950_1_0.pext
    Changelog:
    - 'Initial release'
  - Version: 1.1
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-08-19
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.08.19_7bc43c06/FilterPresetsQuickLauncher_ef9df36c-24c2-418c-8468-eed95a09d950_1_1.pext
    Changelog:
    - 'Updated localizations'
    - 'Added support to display configured images in Search bar Filter presets results'
  - Version: 1.2
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-08-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.08.28_553d8252/FilterPresetsQuickLauncher_ef9df36c-24c2-418c-8468-eed95a09d950_1_2.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.3
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-09-27
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.09.27_1fcfc18d/FilterPresetsQuickLauncher_ef9df36c-24c2-418c-8468-eed95a09d950_1_3.pext
    Changelog:
    - 'Changed: Updated localizations'
  - Version: 1.4
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-10-10
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.10.10_141fd33d/FilterPresetsQuickLauncher_ef9df36c-24c2-418c-8468-eed95a09d950_1_4.pext
    Changelog:
    - 'Changed: Updated localizations'
  - Version: 1.5
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-12-09
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.12.09_996632ce/FilterPresetsQuickLauncher_ef9df36c-24c2-418c-8468-eed95a09d950_1_5.pext
    Changelog:
    - 'Changed: The view will be changed to the library view when applying a filter preset from the sidebar'
  - Version: 1.6
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-02-04
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.02.04_c8608bd5/FilterPresetsQuickLauncher_ef9df36c-24c2-418c-8468-eed95a09d950_1_6.pext
    Changelog:
    - 'Changed: Updated localizations'
  - Version: 1.7
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.03.17_527a9df9/FilterPresetsQuickLauncher_ef9df36c-24c2-418c-8468-eed95a09d950_1_7.pext
    Changelog:
    - 'Changed: Updated localizations'