AddonId: LibraryExporter_54bf64c6-c453-4cbc-92f8-4960b56f930e
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.5.0
    ReleaseDate: 2022-10-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.10.14_4601f7af/LibraryExporter_54bf64c6-c453-4cbc-92f8-4960b56f930e_1_0.pext
    Changelog:
    - 'Initial release'
  - Version: 1.1
    RequiredApiVersion: 6.5.0
    ReleaseDate: 2022-10-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.10.20_fc05e8cf/LibraryExporter_54bf64c6-c453-4cbc-92f8-4960b56f930e_1_1.pext
    Changelog:
    - 'Add support to export Roms property'
    - 'Updated localizations'
  - Version: 1.2
    RequiredApiVersion: 6.5.0
    ReleaseDate: 2022-11-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.11.14_873c946b/LibraryExporter_54bf64c6-c453-4cbc-92f8-4960b56f930e_1_2.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.3
    RequiredApiVersion: 6.5.0
    ReleaseDate: 2023-01-07
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.01.07_6064640d/LibraryExporter_54bf64c6-c453-4cbc-92f8-4960b56f930e_1_3.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.4
    RequiredApiVersion: 6.5.0
    ReleaseDate: 2023-02-06
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.02.06_002184fc/LibraryExporter_54bf64c6-c453-4cbc-92f8-4960b56f930e_1_4.pext
    Changelog:
    - 'Support to configure separator to use in fields with multiple items'
    - 'Updated localizations'
  - Version: 1.5
    RequiredApiVersion: 6.5.0
    ReleaseDate: 2023-02-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.02.15_7796d0ce/LibraryExporter_54bf64c6-c453-4cbc-92f8-4960b56f930e_1_5.pext
    Changelog:
    - 'Updated localizations'
    - 'Updated links'
  - Version: 1.6
    RequiredApiVersion: 6.5.0
    ReleaseDate: 2023-03-26
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.03.26_e5534fd9/LibraryExporter_54bf64c6-c453-4cbc-92f8-4960b56f930e_1_6.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.7
    RequiredApiVersion: 6.5.0
    ReleaseDate: 2023-04-04
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.04.04_79c83647/LibraryExporter_54bf64c6-c453-4cbc-92f8-4960b56f930e_1_7.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.8
    RequiredApiVersion: 6.5.0
    ReleaseDate: 2023-07-19
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.07.19_7051579c/LibraryExporter_54bf64c6-c453-4cbc-92f8-4960b56f930e_1_8.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.9
    RequiredApiVersion: 6.5.0
    ReleaseDate: 2023-08-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.08.18_ceff63a9/LibraryExporter_54bf64c6-c453-4cbc-92f8-4960b56f930e_1_9.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.10
    RequiredApiVersion: 6.5.0
    ReleaseDate: 2023-09-03
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.09.03_e4bd8de7/LibraryExporter_54bf64c6-c453-4cbc-92f8-4960b56f930e_1_10.pext
    Changelog:
    - 'Added support to export Completion Status (By luskynavy)'
  - Version: 1.11
    RequiredApiVersion: 6.5.0
    ReleaseDate: 2024-02-04
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.02.04_c8608bd5/LibraryExporter_54bf64c6-c453-4cbc-92f8-4960b56f930e_1_11.pext
    Changelog:
    - 'Added: Support to export Sorting name'
    - 'Added: Support to export games filtered in view'
    - 'Fixed: Games not being sorted when exporting selected games'
    - 'Changed: Updated localizations'
  - Version: 1.12
    RequiredApiVersion: 6.5.0
    ReleaseDate: 2024-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.03.17_527a9df9/LibraryExporter_54bf64c6-c453-4cbc-92f8-4960b56f930e_1_12.pext
    Changelog:
    - 'Changed: Updated localizations'
  - Version: 1.13
    RequiredApiVersion: 6.5.0
    ReleaseDate: 2024-05-12
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.05.12_b43337e1/LibraryExporter_54bf64c6-c453-4cbc-92f8-4960b56f930e_1_13.pext
    Changelog:
    - 'Changed: Updated localizations'