AddonId: SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_1.pext
    Changelog:
      - Updated localizations
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_2.pext
    Changelog:
    - Updated localizations
    - Rewriten from scratch as a plugin
    - Options are now available in extensions settings section
    - "IMPORTANT NOTE READ: THE EXTENSION CURRENTLY HAS ISSUES WITH GAMES THAT LAUNCH IN WINDOW OR BORDERLESS FULLSCREEN WHEN LAUNCHED IN FULLSCREEN MODE, SINCE MUSIC DOESN'T STOP. THIS WILL BE FIXED IN THE NEXT RELEASE SO FOR NOW EITHER DISABLE THIS PLUGIN OR DISABLE MUSIC IN PLAYNITE!"