AddonId: Steam_Tags_Importer_01b67948-33a1-42d5-bd39-e4e8a226d215
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/Steam_Tags_Importer_01b67948-33a1-42d5-bd39-e4e8a226d215_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/Steam_Tags_Importer_01b67948-33a1-42d5-bd39-e4e8a226d215_2_1.pext
    Changelog:
      - Updated localizations