AddonId: ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.3.0
    ReleaseDate: 2022-07-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.08.21_54d33423/ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3_1_0.pext
    Changelog:
    - 'Initial release'
  - Version: 1.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-10-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.10.20_fc05e8cf/ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3_1_1.pext
    Changelog:
    - 'Added support custom themes to define additional changes to be done when converting layout to Grid View'
    - 'Updated localizations'
  - Version: 1.2
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-01-07
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.01.07_6064640d/ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3_1_2.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.3
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-02-06
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.02.06_002184fc/ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3_1_3.pext
    Changelog:
    - 'Added additional logging'
  - Version: 1.4
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-02-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.02.15_7796d0ce/ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3_1_4.pext
    Changelog:
    - 'Updated links'
  - Version: 1.5
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-04-11
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.04.11_03a5475a/ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3_1_5.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.6
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-08-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.08.28_553d8252/ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3_1_6.pext
    Changelog:
    - 'Added support for "Nova X" theme'
  - Version: 1.7
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-02-04
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.02.04_c8608bd5/ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3_1_7.pext
    Changelog:
    - 'Changed: Updated localizations'
  - Version: 1.8
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.03.17_527a9df9/ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3_1_8.pext
    Changelog:
    - 'Changed: Updated localizations'
  - Version: 1.9
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-05-12
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.05.12_b43337e1/ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3_1_9.pext
    Changelog:
    - 'Changed: Updated localizations'
  - Version: 1.10
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-09-23
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.09.23_6ce05621/ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3_1_10.pext
    Changelog:
    - 'Added: Support to "Stardust (Legacy Layout)" theme'
  - Version: 1.11
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-12-21
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.12.21_6839de06/ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3_1_11.pext
    Changelog:
    - 'Added: Indication to increase Grid View Details panel width to Settings and the notification message, to ensure the converted layout displays correctly.'
    - 'Changed: The extension will now convert all supported themes layouts by default.'
    - 'Fixed: Addressed an issue where the original Grid View Details layout backup file was overwritten if the Details View layout file was modified externally, preventing the restoration of the original layout'
  - Version: 1.12
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2025-04-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2025.04.05_8a0219de/ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3_1_12.pext
    Changelog:
    - 'Changed: Updated localizations for improved language support'