AddonId: ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta3/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_0.pext
    Changelog:
    - Initial release
  - Version: 1.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta3/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_1.pext
    Changelog:
    - Updated localizations
    - Fix videos starting playing at second 1 when repeating
  - Version: 1.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta3/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_2.pext
    Changelog:
    - Fix icons in buttons of video player not showing if font is not installed
  - Version: 1.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta3/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_3.pext
    Changelog:
    - Add NewContextVideoAvailable and IsPlaying settings path available for theme developers
    - Fix source switch button changes not applying when selecting a new game
  - Version: 1.4
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta3/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_4.pext
    Changelog:
    - Updated localizations
  - Version: 1.5
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-22
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta4/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_5.pext
    Changelog:
    - Updated localizations
  - Version: 1.6
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-22
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta4/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_6.pext
    Changelog:
    - Updated localizations
  - Version: 1.7
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_7.pext
    Changelog:
    - Updated localizations
    - Update to PlayniteSDK.6.0.0
    - Option to stream trailer videos from Steam on demand
    - Split logo and video settings in tabs
    - Options to enable or disable logo effect and configure its depth, direction, blur radius and opacity
    - Fix small unresponsiveness when loading logos
  - Version: 1.8
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-01
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_8.pext
    Changelog:
    - Fix playback bar and slider progress being misaligned