AddonId: ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_1.pext
    Changelog:
      - Updated localizations
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta3/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_2.pext
    Changelog:
    - Updated localizations
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_3.pext
    Changelog:
    - Updated localizations
    - Update to PlayniteSDK.6.0.0
  - Version: 2.4
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_4.pext
    Changelog:
    - Updated localizations
    - Improved rate limit handling for metadata requests
  - Version: 2.5
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-16
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_5.pext
    Changelog:
    - Fix in case entry status returned by AniList is null
    - Updated to Playnite SDK 6.1.0
  - Version: 2.6
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_6.pext
    Changelog:
    - Updated localizations
  - Version: 2.7
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_7.pext
    Changelog:
    - Updated localizations
    - Add Play Action functionality, providing options to open the game links.