AddonId: JastUsaLibrary_d407a620-5953-4ca4-a25c-8194c8559381
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.15_9bdaf3ae/JastUsaLibrary_d407a620-5953-4ca4-a25c-8194c8559381_1_0.pext
    Changelog:
    - 'Initial release'
  - Version: 1.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.15_d5401715/JastUsaLibrary_d407a620-5953-4ca4-a25c-8194c8559381_1_1.pext
    Changelog:
    - 'Fix not importing all games from user library'