AddonId: VNDBNexus_39229206-1199-4fee-a014-e8478ea4cd77
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-05-27
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.05.27_832bcd1c/VNDBNexus_39229206-1199-4fee-a014-e8478ea4cd77_1_0.pext
    Changelog:
    - 'Initial release'
  - Version: 1.1
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-05-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.05.28_ec5dadf9/VNDBNexus_39229206-1199-4fee-a014-e8478ea4cd77_1_1.pext
    Changelog:
    - 'Added: Support to change screenshots with arrow keys in the screenshots view window.'
    - 'Fixed: Displaying the incorrect visual novel data in some circumstances when switching between games.'
  - Version: 1.2
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-05-31
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.05.31_256ef517/VNDBNexus_39229206-1199-4fee-a014-e8478ea4cd77_1_2.pext
    Changelog:
    - 'Added: Settings to configure which images should be displayed when displaying a new visual novel'
  - Version: 1.3
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-05-31
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.05.31_4157eed2/VNDBNexus_39229206-1199-4fee-a014-e8478ea4cd77_1_3.pext
    Changelog:
    - 'Changed: Updated localizations for improved language support'
  - Version: 1.4
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-06-03
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.06.03_74640f56/VNDBNexus_39229206-1199-4fee-a014-e8478ea4cd77_1_4.pext
    Changelog:
    - 'Changed: Background metadata download will now also match to the visual novel entry by aliases and alternative titles'
    - 'Changed: Improvements to how the extension how the extension limits and handles the requests made to VNDB to obtain data'
    - 'Fixed: Failing to match the game to the visual novel entry during background metadata download even if it was present in the results'
    - 'Fixed: Certain searches not returning visual novel results'
    - 'Fixed: Visual novel names removing certain characters when imported to game name during metadata download'
    - 'Changed: Updated localizations for improved language support'
  - Version: 1.5
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-06-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.06.05_bfd867aa/VNDBNexus_39229206-1199-4fee-a014-e8478ea4cd77_1_5.pext
    Changelog:
    - 'Added: The VNDB panel will now display the visual novel rating'
    - 'Added: The VNDB panel will now display the visual novel length'
    - 'Added: Implemented support for Playnite Keyboard launcher using the "VN" keyword to search for visual novels. Results can be displayed in either the VNDB panel or opened on the web browser.'
    - 'Changed: Cancelling the metadata download process will now cancel it immediately.'
  - Version: 1.6
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-06-08
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.06.08_d9546671/VNDBNexus_39229206-1199-4fee-a014-e8478ea4cd77_1_6.pext
    Changelog:
    - 'Added: The VNDB panel will now displayed the Average and Weighted scores separately if they are different. Special thanks to Yorhel for updating the VNDB API to make this possible.'
    - 'Fixed: Improvements to how data is obtained in the VNDB panel to prevent issues by downloading data concurrently multiple times, caused by switching to a game back and forth or switching to a different view'
    - 'Fixed: Selecting a characters tab even by default in cases where it does not have available characters due to being hidden by being spoiler characters'
    - 'Fixed: Displaying 0 minutes in length when visual novel length is less than an hour'
    - 'Changed: Updated localizations for improved language support'
  - Version: 1.7
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.09.13_60b1b221/VNDBNexus_39229206-1199-4fee-a014-e8478ea4cd77_1_7.pext
    Changelog:
    - 'Fixed: Failing to obtain tags during metadata download if download of background images is disabled'