AddonId: XboxMetadata_7a663fbb-99b9-4291-a5e1-3ce7f2442b59
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-04-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.04.30_f564ee5e/XboxMetadata_7a663fbb-99b9-4291-a5e1-3ce7f2442b59_1_0.pext
    Changelog:
    - 'Initial release'
  - Version: 1.1
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-05-12
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.05.12_b43337e1/XboxMetadata_7a663fbb-99b9-4291-a5e1-3ce7f2442b59_1_1.pext
    Changelog:
    - ''
  - Version: 1.2
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-05-16
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.05.16_5924b15b/XboxMetadata_7a663fbb-99b9-4291-a5e1-3ce7f2442b59_1_2.pext
    Changelog:
    - ''
  - Version: 1.3
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-05-31
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.05.31_4157eed2/XboxMetadata_7a663fbb-99b9-4291-a5e1-3ce7f2442b59_1_3.pext
    Changelog:
    - ''
  - Version: 1.4
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-06-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.06.05_bfd867aa/XboxMetadata_7a663fbb-99b9-4291-a5e1-3ce7f2442b59_1_4.pext
    Changelog:
    - ''
  - Version: 1.5
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2025-04-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2025.04.05_8a0219de/XboxMetadata_7a663fbb-99b9-4291-a5e1-3ce7f2442b59_1_5.pext
    Changelog:
    - ''