AddonId: VNDBNexus_39229206-1199-4fee-a014-e8478ea4cd77
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-05-27
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.05.27_832bcd1c/VNDBNexus_39229206-1199-4fee-a014-e8478ea4cd77_1_0.pext
    Changelog:
    - 'Initial release'