name: Bug report
title: "[Extension name] Bug description"
description: Report a bug to help us improve
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        **Check for existing issues first**
        Before reporting a bug, please use the issue search to check if the problem has already been reported. This helps avoid duplicates and speeds up resolution.

        **Instructions**
        Change the placeholder title automatically filled in the template and provide the necessary details in the sections below. Fields marked with a * are required.
  - type: checkboxes
    attributes:
      label: Pre-Request Checklist
      description: Before submitting your feature request, please confirm the following
      options:
        - label: "I have checked and confirmed **this is not** a duplicate issue"
          required: true
        - label: "I have verified that I'm using the latest version of the extension by checking for updates in Playnite"
          required: true
        - label: "I have modified the placeholder issue title according to this issue"
          required: true
  - type: input
    attributes:
      label: Extension name
      description: Indicate the extension for which extension this issue is for
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug and what behavior you expected instead.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: If the issue isn't obvious from the description, please list the steps to reproduce the behavior. This is especially important for intermittent issues.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: |
        If the issue caused Playnite to crash or is related to a theme error, please attach the **playnite.log** and **extensions.log** files. 

        - For the portable version of Playnite, the files are located in the Playnite installation directory.
        - For the installed version, you can find them in **%AppData%\Playnite** (type this in the Explorer address bar).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: Add screenshots or videos to help illustrate the issue, if applicable. These are particularly useful for UI or visual bugs. **It also can be very helpful to better convey your issue or idea**
    validations:
      required: false